blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [ 
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('ajax/preview/', views.ajax_preview, name='ajax_preview'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/edit/edit_confirm/', views.edit_confirm, name='edit_confirm'),
    path('tag/<str:tag>', views.tag_view, name='tag'),
    # path('')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from . import settings

static_urlpatterns = [
    # re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path("blog/", include("blog.urls")),
    path('admin/', admin.site.urls),
    path("user/", include("user.urls")),
    path("", include(static_urlpatterns)),
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='index'),
    path('<str:username>', views.user_page, name='user_page'),
]

blog/models.py
from django.db import models
from django.template.defaultfilters import truncatechars

class Author(models.Model):
    username = models.CharField(max_length=100, primary_key=True)
    email = models.EmailField(max_length=100, blank=True)
    description = models.TextField(max_length=500, blank=True, default="")
    github_link = models.CharField(max_length=200, blank=True, default="")
    website = models.CharField(max_length=200, blank=True, default="")
    name = models.CharField(max_length=100, blank=True)
    profile_image = models.CharField(max_length=100, blank=True, default="")

    def __str__(self):
        return self.username

class CV(models.Model):
    class Exp_type(models.TextChoices):
        EDU = "EDU", "Education"
        WORK = "WORK", "Work Experience"

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    exp_type = models.CharField(max_length=10, choices=Exp_type.choices, default=Exp_type.WORK)
    position = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    responsibility = models.TextField(default="", blank=True)
    projects = models.TextField(default="", blank=True)
    technologies = models.TextField(default="", blank=True)
    reference = models.TextField(default="", blank=True)

    date_start = models.DateTimeField()
    date_end = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.exp_type}-{self.position}"

class Genre(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Content(models.Model):
    title = models.CharField(max_length=100)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    github_link = models.CharField(max_length=200, blank=True, default="")
    # abstract = models.TextField(max_length=500, blank=True, default="")
    body = models.CharField(max_length=200, blank=True, default="")
    thumbnail = models.CharField(max_length=200, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag = models.CharField(max_length=200, blank=True, default="")

    @property
    def body_display(self):
        return truncatechars(self.body, 200)

    def __str__(self):
        return self.title

#test fix issue

blog/forms.py
from django import forms
from .models import Content

class BlogForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ["title", "genre", "author", "github_link", "body", "tag"]

    file_upload = forms.FileField(label='Or select a file (.md)', required=False)
    thumbnail = forms.ImageField(label='Select a thumbnail', required=False)
        

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from .models import Content, Author, Genre
from . import md_converter
from django.urls import reverse
from django.utils import timezone
from .forms import BlogForm
import os 
import json
from . import utils

class IndexView(generic.ListView):
    template_name = 'blog/index2.html'
    context_object_name = 'latest_blog_list'

    def get_queryset(self):
        """Return all blog"""
        latest_blog_list = Content.objects.filter(created_at__lte=timezone.now()).order_by('-created_at')[:5]
        for blog in latest_blog_list:
            md_text = utils.read_md_file(blog.body)
            blog.body = md_text[:100]

        return latest_blog_list

def tag_view(request, tag):
    blog_list = Content.objects.filter(tag__contains=tag).order_by('-created_at')

    return render(request, 'blog/index2.html', {'latest_blog_list': blog_list})

def detail(request, pk):
    blog = get_object_or_404(Content, pk=pk)
    md_text = utils.read_md_file(blog.body)
    html_text = md_converter.md_convert(md_text)
    blog.body = html_text
    blog.tag = [tag for tag in blog.tag.split(',') if tag.replace(" ","") != '']
    return render(request, 'blog/detail2.html', {'blog': blog})

def add(request):
    print("here")
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            has_file = False
            has_text = False
            print("valid")
            blog = form.save(commit=False)
            if request.FILES.get('file_upload', False):
                file = request.FILES['file_upload']
                if str(file)[-3:] != '.md':
                    print("[Error] File type not supported")
                    return render(request, 'blog/add.html', {'form': form, 'error_message': 'File type not supported'})
                has_file = True
            else:
                print('No file upload')

            if blog.body != '':
                has_text = True

            if has_file == True:
                blog.body = utils.handle_uploaded_file(file, blog.title)
            else:
                if has_text == True:
                    blog.body = utils.save_md_to_file(blog.body, blog.title)
                else:
                    return render(request, 'blog/add.html', {'form': form, 'error_message': 'Enter something in the body or upload a md file'})

            if request.FILES.get('thumbnail', False):
                thumbnail = request.FILES['thumbnail']
                print("thumbnail uploaded")                
                file_path = utils.save_image(thumbnail, blog.title)
                file_path_to_save = "/".join(file_path.split("/")[2:])
                blog.thumbnail = str(file_path_to_save)
            else:
                print("no thumbnail uploaded. choose a random one.")
                blog.thumbnail = utils.get_random_thumbnail(blog.title)

            blog.updated_at = timezone.now()
            blog.save()
            return HttpResponseRedirect(reverse('blog:index'))
    else:
        form = BlogForm()
    return render(request, 'blog/add.html', {'form': form})

def ajax_preview(request):
    if request.is_ajax() or request.method == 'POST':
        print("ajax here")
        body = request.POST.get('mdtext', "")
        body = md_converter.md_convert(body[1:-1].replace(r'\n', '\n'))
        
        return HttpResponse(json.dumps({'html_output': body}), content_type="application/json", status=200)
    else:
        return HttpResponse("")

def edit(request, pk):
    blog = get_object_or_404(Content, pk=pk)
    md_text = utils.read_md_file(blog.body)
    blog.body = md_text

    return render(request, 'blog/edit.html', {'blog': blog})

def edit_confirm(request, pk):
    blog = get_object_or_404(Content, pk=pk)
    if request.method == 'POST':
        title = request.POST.get("title", "")
        md_text = request.POST.get("markdown_text", "")

        valid = True
        if title != "":
            blog.title = title
        else:
            valid = False
        if md_text != "":
            file_path = blog.body
            utils.update_md_file(file_path, md_text)
        else:
            valid = False

        if valid:
            blog.updated_at = timezone.now()
            blog.save()
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            print("invalid")
            blog.body = md_text
            return render(request, 'blog/edit.html', {'blog': blog, 'error_message': 'Empty title or body'})
    else:
        md_text = utils.read_md_file(blog.body)
        html_text = md_converter.md_convert(md_text)
        blog.body = html_text
        return render(request, 'blog/edit.html', {'blog': blog})

blog/templates/blog/add.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous">
</script>
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}" >  
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">

<html lang="en">
    <h1>Add a new blog post</h1>
    <form action="{% url 'blog:add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if error_message %}<p class="error_message">{{ error_message }}</p>{% endif %}
        <input class="button" type="submit" value="Add">
    </form>
</html>

blog/templates/blog/detail.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous">
</script>
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}" >  
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

<h1>Blog Info</h1> 

<li><b> Title:</b> {{ blog.title }}</li>
<li><b> Genre:</b> {{ blog.genre }}</li>
<li><b> Content:</b> 
    {% autoescape off %}
    {{ blog.body }}
    {% endautoescape %}
</li>

<a class="button" href="{% url 'blog:edit' blog.id %}">Edit post</a>

blog/templates/blog/edit.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous">
</script>
<link rel="stylesheet"  href="{% static 'blog/css/bootstrap.min.css' %}" >  
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet"  href="{% static 'blog/style.css' %}">
<script src="{% static 'blog/js/md.js' %}"></script>

<h1>Blog editor</h1> 

<form action="{% url 'blog:edit_confirm' blog.id %}" method="post" id="editform">
    {% csrf_token %}
    <li><label for="title">Title:</label> <input type="text" id="title" name="title" value="{{ blog.title }}"></input></li>

    <input type="submit" value="Submit">

</form> 

<li><label for="body">Body:</label>
<div class="container"  style="padding:3px;">
    <div id="mdedit-body" style="padding:3px; position: relative; top:0; bottom:0; left:0; right:0" class="row">
        <div style="height:100%; width:50%" class="col-sm-6">
            <textarea style="font-family: monospace; font-size: medium; color:#222; width:100%; height:100%" id="markdown_input" cols="80" rows="30" name="markdown_text" form="editform">{{blog.body}}</textarea>
        </div>
        <div style="height:100%; width:50%; padding-left:0px" class="col-sm-6">
            <div class="html-output markdown-body border rounded-top" id="html_result" style=" height:100%"></div>
        </div>
    </div>
</div>
    


    {% if error_message %}<p class="error_message">{{ error_message }}</p>{% endif %}

blog/templates/blog/index.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous">
</script>
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}" >  
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">

{% if latest_blog_list %}
  {% for blog in latest_blog_list %}
    <ul>
      <li>
        <img src="{% static blog.thumbnail %}" alt="{{ blog.title }}" width="200" height="300"></img>
        <a href="{% url 'blog:detail' blog.id %}">{{ blog.id }}: {{ blog.title }}</a>
      </li>
    </ul>
  {% endfor %}
{% endif %}

<!-- A button for adding a new blog post -->
<a class="button" href="{% url 'blog:add' %}">New post</a>

blog/templates/blog/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="Ha Nguyen">

<title>Ha Nguyen Blog</title>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}" >
<!-- Fonts -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static 'blog/css/mediumish.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'blog/css/postboot.min.css' %}" type="text/css" rel="stylesheet">

</head>
<body>

<!-- Begin Nav
================================================== -->
<nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">
<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="container">
	<!-- Begin Logo -->
	<a class="navbar-brand" href="{% url 'blog:index' %}">
	<img src="{% static 'blog/img/logo-h.png' %}" alt="logo">
	</a>
	<!-- End Logo -->
	<div class="collapse navbar-collapse" id="navbarsExampleDefault">
		<!-- Begin Menu -->
		<ul class="navbar-nav ml-auto">
			<li class="nav-item active">
			<a class="nav-link" href="{% url 'blog:index' %}">Stories <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'blog:index' %}">Post</a>
			</li>
			<!-- <li class="nav-item">
			<a class="nav-link" href="{% url 'blog:index' %}">Author</a>
			</li> -->
		</ul>
		<!-- End Menu -->
		<!-- Begin Search -->
		<form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="text" placeholder="Search">
			<span class="search-icon"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path></svg></span>
		</form>
		<!-- End Search -->
	</div>
</div>
</nav>
<!-- End Nav
================================================== -->

<!-- Begin Site Title
================================================== -->
<div class="container">
	<div class="mainheading">
		<h1 class="sitetitle">Ha Nguyen's Blog</h1>
		<p class="lead">
			Hello
		</p>
	</div>
<!-- End Site Title
================================================== -->

	<!-- Begin Featured
	================================================== -->
	<section class="featured-posts">
	<div class="section-title">
		<h2><span>Featured Post</span></h2>
	</div>
	<div class="card-columns listfeaturedtag">

	{% if latest_blog_list %}
		{% for blog in latest_blog_list %}	
		<!-- begin post -->
		<div class="card">
			<div class="row">
				<div class="col-md-5 wrapthumbnail">
					<a href="{% url 'blog:detail' blog.id %}">
						<div class="thumbnail" style="background-image:url(/{{ blog.thumbnail }});">
						</div>
					</a>
					<!-- <img class="card-img-sm-left" src="{% static blog.thumbnail %}"> -->
				</div> 
				<div class="col-md-7">
					<!-- <div class="card"> -->
						<div class='card-body'>
							<h2 class="card-title"><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h2>
							<h4 class="card-text">{{ blog.body }}</h4>
							<div class="metafooter">
								<div class="wrapfooter">
									<span class="meta-footer-thumb">
									<a href="{% url 'user:user_page' blog.author.username %}"><img class="author-thumb" src="https://www.gravatar.com/avatar/e56154546cf4be74e393c62d1ae9f9d4?s=250&amp;d=mm&amp;r=x" alt="{{ blog.author.username }}"></a>
									</span>
									<span class="author-meta">
									<span class="post-name"><a href="{% url 'user:user_page' blog.author.username %}">{{ blog.author }}</a></span><br/>
									<span class="post-date">{{ blog.created_at|date  }}</span><span class="dot"></span><span class="post-read">6 min read</span>
									</span>
									<span class="post-read-more"><a href="{% url 'blog:detail' blog.id %}" title="Read Story"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M19 6c0-1.1-.9-2-2-2H8c-1.1 0-2 .9-2 2v14.66h.012c.01.103.045.204.12.285a.5.5 0 0 0 .706.03L12.5 16.85l5.662 4.126a.508.508 0 0 0 .708-.03.5.5 0 0 0 .118-.285H19V6zm-6.838 9.97L7 19.636V6c0-.55.45-1 1-1h9c.55 0 1 .45 1 1v13.637l-5.162-3.668a.49.49 0 0 0-.676 0z" fill-rule="evenodd"></path></svg></a></span>
								</div>
							</div>
						</div>
					<!-- </div> -->
				</div>
			</div>
		</div>
		<!-- end post -->
		{% endfor %}
	{% endif %}

	</div>
	</section>
	<!-- End Featured
	================================================== -->

	<!-- Begin List Posts
	================================================== -->
	<!-- <section class="recent-posts">
	<div class="section-title">
		<h2><span>All Stories</span></h2>
	</div>
	<div class="card-columns listrecent"> -->
		<!-- begin post -->
		<!-- <div class="card">
			<a href="post.html">
				<img class="img-fluid" src="assets/img/demopic/10.jpg" alt="">
			</a>
			<div class="card-block">
				<h2 class="card-title"><a href="post.html">Visiting the world means learning cultures</a></h2>
				<h4 class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</h4>
				<div class="metafooter">
					<div class="wrapfooter">
						<span class="meta-footer-thumb">
						<a href="author.html"><img class="author-thumb" src="https://www.gravatar.com/avatar/e56154546cf4be74e393c62d1ae9f9d4?s=250&amp;d=mm&amp;r=x" alt="Sal"></a>
						</span>
						<span class="author-meta">
						<span class="post-name"><a href="author.html">Sal</a></span><br/>
						<span class="post-date">22 July 2017</span><span class="dot"></span><span class="post-read">6 min read</span>
						</span>
						<span class="post-read-more"><a href="post.html" title="Read Story"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M19 6c0-1.1-.9-2-2-2H8c-1.1 0-2 .9-2 2v14.66h.012c.01.103.045.204.12.285a.5.5 0 0 0 .706.03L12.5 16.85l5.662 4.126a.508.508 0 0 0 .708-.03.5.5 0 0 0 .118-.285H19V6zm-6.838 9.97L7 19.636V6c0-.55.45-1 1-1h9c.55 0 1 .45 1 1v13.637l-5.162-3.668a.49.49 0 0 0-.676 0z" fill-rule="evenodd"></path></svg></a></span>
					</div>
				</div>
			</div>
		</div> -->
		<!-- end post -->
	<!-- </div>
	</section> -->
	<!-- End List Posts
	================================================== -->

	<!-- Begin Footer
	================================================== -->
	<div class="footer">
		<p class="pull-left">
			 Copyright &copy; 2021 Ha Nguyen
		</p>
		<p class="pull-right">
			 By <a target="_blank" href="https://github.com/habom2310">HaBom</a>
		</p>
		<div class="clearfix">
		</div>
	</div>
	<!-- End Footer
	================================================== -->

</div>
<!-- /.container -->

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'blog/js/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/js/ie10-viewport-bug-workaround.js' %}"></script>
<script src="{% static 'blog/js/postboot.min.js' %}"></script>
</body>
</html>