blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [ 
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('ajax/preview/', views.ajax_preview, name='ajax_preview'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/edit/edit_confirm/', views.edit_confirm, name='edit_confirm'),
    path('tag/<str:tag>', views.tag_view, name='tag'),
    # path('')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from . import settings

static_urlpatterns = [
    # re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path("blog/", include("blog.urls")),
    path('admin/', admin.site.urls),
    path("user/", include("user.urls")),
    path("", include(static_urlpatterns)),
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='index'),
    path('<str:username>', views.user_page, name='user_page'),
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Author, Content
from blog.md_converter import md_convert
# Create your views here.

def user_page(request, username):
    user = get_object_or_404(Author, username=username)
    blog_list = Content.objects.filter(author=user).order_by('-created_at')

    context = {
        'user': user,
        'latest_blog_list': blog_list,
    }
    print(context)

    return render(request, 'user/user.html', context)

user/templates/user/user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="Ha Nguyen">

<title>Ha Nguyen Blog</title>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}" >
<!-- Fonts -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static 'blog/css/mediumish.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'blog/css/postboot.min.css' %}" type="text/css" rel="stylesheet">

</head>
<body>

<!-- Begin Nav
================================================== -->
<nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">
<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="container">
	<!-- begin logo -->
	<a class="navbar-brand" href="index.html">
    <img src="{% static 'blog/img/logo-h.png' %}" alt="logo">
  </a>
	<!-- end logo -->
	<div class="collapse navbar-collapse" id="navbarsExampleDefault">
		<!-- begin menu -->
		<ul class="navbar-nav ml-auto">
			<li class="nav-item active">
			<a class="nav-link" href="{% url 'blog:index' %}">Stories <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'blog:index' %}">Post</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'blog:index' %}">Author</a>
			</li>
		</ul>
		<!-- end menu -->
		<!-- begin search -->
		<form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="text" placeholder="Search">
			<span class="search-icon"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path></svg></span>
		</form>
		<!-- end search -->
	</div>
</div>
</nav>
<!-- End Nav
================================================== -->

<!-- Begin Top Author Page
================================================== -->
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8 col-md-offset-2">
			<div class="mainheading">
				<div class="row post-top-meta authorpage">
					<div class="col-md-10 col-xs-12">
						<h1>{{ user.name }}</h1>
						<span class="author-description">{{ user.description }}</span>
						<div class="sociallinks"><a  target="_blank" href="{{ user.github_link }}"><i class="fa fa-github"></i></a> <span class="dot"></span> <a target="_blank" href="{{ user.website }}"><i class="fa fa-font-awesome"></i></a></div>
						
					</div>
					<div class="col-md-2 col-xs-12">
						<img class="author-thumb" src="https://www.gravatar.com/avatar/e56154546cf4be74e393c62d1ae9f9d4?s=250&amp;d=mm&amp;r=x" alt="{{ user.name }}">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Top Author Meta
================================================== -->

<!-- Begin Author Posts
================================================== -->
<div class="graybg authorpage">
	<div class="container">
		<div class="listrecent listrelated">
		{% if latest_blog_list %}
			{% for blog in latest_blog_list %}	

				<!-- begin post -->
				<div class="authorpostbox">
					<div class="card">
						<a href="{% url 'user:user_page' user.username %}">
						<img class="img-fluid img-thumb" src="assets/img/demopic/8.jpg" alt="">
						</a>
						<div class="card-block">
							<h2 class="card-title"><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h2>
              				<h4 class="card-text">{{ blog.body }}</h4>
            				<div class="metafooter">
								<div class="wrapfooter">
									<span class="meta-footer-thumb">
									<a href="{% url 'user:user_page' user.username %}"><img class="author-thumb" src="https://www.gravatar.com/avatar/e56154546cf4be74e393c62d1ae9f9d4?s=250&amp;d=mm&amp;r=x" alt="{{ author.username }}"></a>
									</span>
									<span class="author-meta">
									<span class="post-name"><a href="{% url 'user:user_page' user.username %}">{{ user.name }}</a></span><br/>
									<span class="post-date">{{ blog.created_at }}</span><span class="dot"></span><span class="post-read">6 min read</span>
									</span>
									<span class="post-read-more"><a href="{% url 'blog:detail' blog.id %}" title="Read Story"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M19 6c0-1.1-.9-2-2-2H8c-1.1 0-2 .9-2 2v14.66h.012c.01.103.045.204.12.285a.5.5 0 0 0 .706.03L12.5 16.85l5.662 4.126a.508.508 0 0 0 .708-.03.5.5 0 0 0 .118-.285H19V6zm-6.838 9.97L7 19.636V6c0-.55.45-1 1-1h9c.55 0 1 .45 1 1v13.637l-5.162-3.668a.49.49 0 0 0-.676 0z" fill-rule="evenodd"></path></svg></a></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- end post -->
			{% endfor %}
		{% endif %}
		</div>
	</div>
</div>
<!-- End Author Posts
================================================== -->

<!-- Begin Twitter Timeline
================================================== -->
<!-- End Twitter Timeline
================================================== -->

<!-- Begin Footer
================================================== -->
<div class="container">
	<div class="footer">
		<p class="pull-left">
			 Copyright &copy; 2021 Ha Nguyen
		</p>
		<p class="pull-right">
			 By <a target="_blank" href="https://github.com/habom2310">HaBom</a>
		</p>
		<div class="clearfix">
		</div>
	</div>
</div>
<!-- End Footer
================================================== -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'blog/js/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/js/ie10-viewport-bug-workaround.js' %}"></script>
<script src="{% static 'blog/js/postboot.min.js' %}"></script>
</body>
</html>